name: Connect Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository
      - uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Display root directory contents
        run: ls -la

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_VIJI_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_VIJI_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t vijisomu10/test_dockerhub:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push vijisomu10/test_dockerhub:latest
